[package]
name = "topics"
version = "0.1.0"
edition = "2024"

[dependencies]
packet_trait = { path = "../packet_trait" }
heapless = { version = "0.9.2", features = ["serde"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }